# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: coda
    main: ./cmd/coda
    binary: coda
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug Fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Performance Improvements'
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 2
    - title: 'Code Refactoring'
      regexp: "^.*refactor[(\\w)]*:+.*$"
      order: 3
    - title: Other
      order: 999

release:
  github:
    owner: common-creation
    name: coda
  draft: true
  prerelease: auto
  mode: replace
  header: |
    ## CODA Release {{ .Tag }}
    
    ### Installation
    
    #### macOS/Linux
    ```bash
    curl -sSL https://github.com/common-creation/coda/releases/download/{{ .Tag }}/coda_{{ .Os }}_{{ .Arch }}.tar.gz | tar xz
    sudo mv coda /usr/local/bin/
    ```
    
    #### Windows
    Download the Windows zip file and extract it to a directory in your PATH.
    
  footer: |
    ---
    **Full Changelog**: https://github.com/common-creation/coda/compare/{{ .PreviousTag }}...{{ .Tag }}

# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj